export interface Emotion {
  id: string;
  label: string;
}

export const EMOTIONS: Emotion[] = [
  { id: 'apatia', label: 'Апатія' },
  { id: 'appetite', label: 'Апетит' },
  { id: 'alertness', label: 'Бадьорість' },
  { id: 'desire_to_worry', label: 'Бажання турбуватися' },
  { id: 'desire_for_solitude', label: 'Бажання усамітнення' },
  { id: 'indifference', label: 'Байдужість' },
  { id: 'helplessness', label: 'Безсилля' },
  { id: 'insomnia', label: 'Безсоння' },
  { id: 'carefreeness', label: 'Безтурботність' },
  { id: 'bliss', label: 'Блаженство' },
  { id: 'back_pain', label: 'Біль у попереку' },
  { id: 'rib_pain', label: 'Біль у ребрах' },
  { id: 'back_pain', label: 'Біль у спині' },
  { id: 'pelvic_pain', label: 'Біль у тазі' },
  { id: 'heaviness', label: 'Важкість' },
  { id: 'gratitude', label: 'Вдячність' },
  { id: 'milk_leakage', label: 'Виділення молозива' },
  { id: 'fetal_movement', label: 'Ворушіння' },
  { id: 'vulnerability', label: 'Вразливість' },
  { id: 'balance', label: 'Врівноваженість' },
  { id: 'fatigue', label: 'Втома' },
  { id: 'openness', label: 'Відкритість' },
  { id: 'responsibility', label: 'Відповідальність' },
  { id: 'disgust', label: 'Відраза' },
  { id: 'harmony', label: 'Гармонія' },
  { id: 'hiccups', label: 'Гикавка малюка' },
  { id: 'anger', label: 'Гнів' },
  { id: 'headache', label: 'Головний біль' },
  { id: 'pride', label: 'Гордість' },
  { id: 'depression', label: 'Депресія' },
  { id: 'imbalance', label: 'Дисбаланс' },
  { id: 'discomfort', label: 'Дискомфорт' },
  { id: 'trust', label: 'Довіра' },
  { id: 'euphoria', label: 'Ейфорія' },
  { id: 'emotionality', label: 'Емоційність' },
  { id: 'energy', label: 'Енергія' },
  { id: 'unity', label: 'Єднання' },
  { id: 'hair_oiliness', label: 'Жирність волосся' },
  { id: 'femininity', label: 'Жіночність' },
  { id: 'forgetfulness', label: 'Забудькуватість' },
  { id: 'enhanced_smell', label: 'Загострення нюху' },
  { id: 'shortness_of_breath', label: 'Задишка' },
  { id: 'satisfaction', label: 'Задоволення' },
  { id: 'satisfaction_with_appearance', label: 'Задоволеність зовнішністю' },
  { id: 'envy', label: 'Заздрість' },
  { id: 'constipation', label: 'Закреп' },
  { id: 'introversion', label: 'Замкнутість' },
  { id: 'exhaustion', label: 'Занепад сил' },
  { id: 'dizziness', label: 'Запаморочення' },
  { id: 'denial', label: 'Заперечення' },
  { id: 'security', label: 'Захищеність' },
  { id: 'fascination', label: 'Захоплення' },
  { id: 'interest', label: 'Зацікавленість' },
  { id: 'embarrassment', label: 'Збентеження' },
  { id: 'weight_gain', label: 'Збільшення ваги' },
  { id: 'connection', label: "Зв'язок" },
  { id: 'surprise', label: 'Здивування' },
  { id: 'bloating', label: 'Здуття' },
  { id: 'libido_change', label: 'Зміна лібідо' },
  { id: 'taste_change', label: 'Зміна смаків' },
  { id: 'shifting_priorities', label: 'Зміщення пріоритетів' },
  { id: 'maturity', label: 'Зрілість' },
  { id: 'impulsivity', label: 'Імпульсивність' },
  { id: 'intuition', label: 'Інтуїція' },
  { id: 'infantilism', label: 'Інфантильність' },
  { id: 'regret', label: 'Каяття' },
  { id: 'complexes', label: 'Комплекси' },
  { id: 'concentration', label: 'Концентрація' },
  { id: 'nightmares', label: 'Кошмари' },
  { id: 'creativity', label: 'Креативність' },
  { id: 'chalky_cravings', label: 'Крейдяні бажання' },
  { id: 'self_criticism', label: 'Критика до себе' },
  { id: 'brittleness_of_nails', label: 'Ламкість нігтів' },
  { id: 'lightness', label: 'Легкість' },
  { id: 'lethargy', label: 'Летаргія' },
  { id: 'love', label: 'Любов' },
  { id: 'laziness', label: 'Лінь' },
  { id: 'maternal_instinct', label: 'Материнський інстинкт' },
  { id: 'metallic_aftertaste', label: 'Металевий присмак' },
  { id: 'butterflies_in_stomach', label: 'Метелики в животі' },
  { id: 'motivation', label: 'Мотивація' },
  { id: 'dreaminess', label: 'Мрійливість' },
  { id: 'swelling', label: 'Набряки' },
  { id: 'hope', label: 'Надія' },
  { id: 'fullness', label: 'Наповненість' },
  { id: 'tension', label: 'Напруга' },
  { id: 'pleasure', label: 'Насолода' },
  { id: 'inspiration', label: 'Натхнення' },
  { id: 'discontent', label: 'Невдоволення' },
  { id: 'insecurity', label: 'Невпевненість' },
  { id: 'clumsiness', label: 'Незграбність' },
  { id: 'nervousness', label: 'Нервозність' },
  { id: 'impatience', label: 'Нетерплячість' },
  { id: 'carelessness', label: 'Неуважність' },
  { id: 'nostalgia', label: 'Ностальгія' },
  { id: 'nausea', label: 'Нудота' },
  { id: 'boredom', label: 'Нудьга' },
  { id: 'tenderness', label: 'Ніжність' },
  { id: 'caution', label: 'Обережність' },
  { id: 'offense', label: 'Образа' },
  { id: 'chills', label: 'Озноб' },
  { id: 'roundness', label: 'Округлість' },
  { id: 'renewal', label: 'Оновлення' },
  { id: 'numbness', label: 'Оніміння' },
  { id: 'optimism', label: 'Оптимізм' },
  { id: 'organization', label: 'Організованість' },
  { id: 'expectation', label: 'Очікування' },
  { id: 'miracle_expectation', label: 'Очікування дива' },
  { id: 'panic', label: 'Паніка' },
  { id: 'premonition', label: 'Передчуття' },
  { id: 'reevaluation_of_values', label: 'Переоцінка цінностей' },
  { id: 'mood_swings', label: 'Перепади настрою' },
  { id: 'rebirth', label: 'Переродження' },
  { id: 'pessimism', label: 'Песимізм' },
  { id: 'heartburn', label: 'Печія' },
  { id: 'tearfulness', label: 'Плаксивість' },
  { id: 'prickling', label: 'Поколювання' },
  { id: 'relief', label: 'Полегшення' },
  { id: 'emptiness', label: 'Порожнеча' },
  { id: 'need_for_communication', label: 'Потреба в спілкуванні' },
  { id: 'need_for_care', label: 'Потреба в турботі' },
  { id: 'jerks', label: 'Поштовхи' },
  { id: 'attractiveness', label: 'Привабливість' },
  { id: 'acceptance', label: 'Прийняття' },
  { id: 'hot_flashes', label: 'Припливи жару' },
  { id: 'passion', label: 'Пристрасть' },
  { id: 'guilt', label: 'Провина' },
  { id: 'productivity', label: 'Продуктивність' },
  { id: 'procrastination', label: 'Прокрастинація' },
  { id: 'enlightenment', label: 'Просвітлення' },
  { id: 'pigmentation', label: 'Пігментація' },
  { id: 'elevation', label: 'Піднесення' },
  { id: 'suspicion', label: 'Підозра' },
  { id: 'joy', label: 'Радість' },
  { id: 'jealousy', label: 'Ревнощі' },
  { id: 'risk', label: 'Ризик' },
  { id: 'rhinitis_pregnant', label: 'Риніт вагітних' },
  { id: 'irritation', label: 'Роздратування' },
  { id: 'relaxation', label: 'Розслабленість' },
  { id: 'absentmindedness', label: 'Розсіяність' },
  { id: 'stretch_marks', label: 'Розтяжки' },
  { id: 'determination', label: 'Рішучість' },
  { id: 'loneliness', label: 'Самотність' },
  { id: 'itching', label: 'Свербіж' },
  { id: 'sexuality', label: 'Сексуальність' },
  { id: 'sentimentality', label: 'Сентиментальність' },
  { id: 'strength', label: 'Сила' },
  { id: 'nesting_syndrome', label: 'Синдром гніздування' },
  { id: 'uterine_contractions', label: 'Скорочення матки' },
  { id: 'weakness', label: 'Слабкість' },
  { id: 'drowsiness', label: 'Сонливість' },
  { id: 'shyness', label: "Сором'язливість" },
  { id: 'calm', label: 'Спокій' },
  { id: 'stability', label: 'Стабільність' },
  { id: 'fear', label: 'Страх' },
  { id: 'stress', label: 'Стрес' },
  { id: 'cramps', label: 'Судоми' },
  { id: 'doubt', label: 'Сумніви' },
  { id: 'dry_skin', label: 'Сухість шкіри' },
  { id: 'creative_rise', label: 'Творчий підйом' },
  { id: 'patience', label: 'Терпіння' },
  { id: 'toxicosis', label: 'Токсикоз' },
  { id: 'tone', label: 'Тонус' },
  { id: 'bargain', label: 'Торг' },
  { id: 'shivering', label: 'Тремтіння' },
  { id: 'anxiety', label: 'Тривога' },
  { id: 'brain_fog', label: 'Туман в голові' },
  { id: 'cravings_sour', label: 'Тяга до кислого' },
  { id: 'cravings_sweet', label: 'Тяга до солодкого' },
  { id: 'cravings_salty', label: 'Тяга до солоного' },
  { id: 'calmness', label: 'Умиротворення' },
  { id: 'chaos', label: 'Хаос' },
  { id: 'excitement', label: 'Хвилювання' },
  { id: 'curiosity', label: 'Цікавість' },
  { id: 'sensitivity', label: 'Чутливість' },
  { id: 'gum_sensitivity', label: 'Чутливість ясен' },
  { id: 'sensuality', label: 'Чуттєвість' },
  { id: 'happiness', label: 'Щастя' },
  { id: 'vivid_dreams', label: 'Яскраві сновидіння' },
  { id: 'clarity_of_mind', label: 'Ясність думки' },
];
